//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wuyiju.Web {
    
    
    public partial class Ask {
        
        /// <summary>
        /// Loop7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop7;
        
        /// <summary>
        /// Zoujunjudian control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Zoujunjudian;
        
        /// <summary>
        /// Loop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop1;
        
        /// <summary>
        /// Loop2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop2;
        
        /// <summary>
        /// Loop3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop3;
        
        /// <summary>
        /// Loop4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop4;
        
        /// <summary>
        /// Loop5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop5;
        
        /// <summary>
        /// Loop6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Wuyiju.Web.Utils.Controls.Loop Loop6;
    }
}
